# Generated by Django 4.0 on 2023-01-30 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_hotel_city'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotel',
            name='City',
            field=models.CharField(max_length=150),
        ),
    ]
