# Generated by Django 4.0 on 2023-02-06 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_room'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hotel',
            name='room_count',
        ),
        migrations.RemoveField(
            model_name='room',
            name='hotel',
        ),
        migrations.AddField(
            model_name='hotel',
            name='Adult',
            field=models.IntegerField(default=None),
        ),
        migrations.AddField(
            model_name='hotel',
            name='Childern',
            field=models.IntegerField(default=None),
        ),
        migrations.AddField(
            model_name='hotel',
            name='room',
            field=models.ManyToManyField(to='home.Room'),
        ),
    ]
