# Generated by Django 4.0 on 2023-01-04 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hotels_data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Hotel_Name', models.CharField(max_length=150)),
                ('Check_In', models.IntegerField()),
                ('Check_Out', models.IntegerField()),
                ('Rooms', models.IntegerField()),
                ('Adult', models.IntegerField()),
                ('Children', models.IntegerField()),
            ],
        ),
    ]
