# Generated by Django 4.0 on 2023-01-24 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='all_hotels_list',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hotel_name', models.CharField(max_length=150)),
                ('hotel_price', models.IntegerField()),
                ('hotel_img', models.ImageField(default='0.jpeg', upload_to='media')),
                ('hotel_rating', models.IntegerField()),
            ],
        ),
    ]
