# Generated by Django 4.0 on 2023-01-27 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0003_all_hotels_list_city'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking_details',
            name='Hotel_Name',
        ),
        migrations.AddField(
            model_name='booking_details',
            name='Hotel_Name',
            field=models.ManyToManyField(to='hotels.hotel_list'),
        ),
    ]
