# Generated by Django 4.0 on 2023-01-30 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel',
            name='City',
            field=models.CharField(max_length=150, null=True),
        ),
    ]
