# Generated by Django 4.0 on 2023-01-23 12:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='hotel_list',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('City', models.CharField(blank=True, max_length=150)),
                ('Hotel_Name', models.CharField(max_length=100)),
                ('Room', models.IntegerField(default=None)),
                ('Adult', models.IntegerField(blank=True)),
                ('Children', models.IntegerField(blank=True)),
                ('Hotel_Image', models.ImageField(default='0.jpeg', upload_to='media')),
            ],
        ),
        migrations.CreateModel(
            name='Hotels_data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('City', models.CharField(blank=True, max_length=150)),
                ('Check_In', models.DateField(blank=True)),
                ('Check_Out', models.DateField(blank=True)),
                ('Rooms', models.IntegerField(blank=True)),
                ('Adult', models.IntegerField(blank=True)),
                ('Children', models.IntegerField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField()),
                ('category', models.CharField(choices=[('YAC', 'AC'), ('NAC', 'NON-AC'), ('DEL', 'DELUXE'), ('KIN', 'KING'), ('QUE', 'QUEEN')], max_length=3)),
                ('beds', models.IntegerField()),
                ('capacity', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Booking_details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Hotel_Image', models.ImageField(default='0.jpeg', upload_to='media')),
                ('Hotel_Price', models.IntegerField()),
                ('Hotel_Rating', models.IntegerField()),
                ('Hotel_Name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hotels.hotel_list')),
            ],
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('check_in', models.DateTimeField()),
                ('check_out', models.DateTimeField()),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hotels.room')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth.user')),
            ],
        ),
    ]
